/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_v1_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goal/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_api_v1_goal_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel Run */
        delete: operations["cancel_run_api_v1_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Input Image */
        get: operations["input_image_api_v1_runs__run_id__input_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/iterations/{index}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Iteration Image */
        get: operations["iteration_image_api_v1_runs__run_id__iterations__index__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/final": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Final Image */
        get: operations["final_image_api_v1_runs__run_id__final_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        /** Save Profile */
        post: operations["save_profile_api_v1_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Profile */
        get: operations["load_profile_api_v1_profiles__filename__get"];
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_v1_profiles__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdditionalInfo */
        AdditionalInfo: {
            /** Reference Photo */
            reference_photo?: string | null;
            /** Custom Notes */
            custom_notes?: string | null;
            /** Preset Used */
            preset_used?: string | null;
        };
        /** AdvancedSettings */
        AdvancedSettings: {
            /** @default Professional Flash */
            lighting: components["schemas"]["Lighting"];
            /** @default Professional */
            mood: components["schemas"]["Mood"];
            /** @default Not Specified */
            age_range: components["schemas"]["AgeRange"];
            /** @default Not Specified */
            gender: components["schemas"]["Gender"];
            /** @default Not Specified */
            ethnicity: components["schemas"]["Ethnicity"];
            /** @default 1024x1024 (Standard) */
            resolution: components["schemas"]["Resolution"];
        };
        /**
         * AgeRange
         * @enum {string}
         */
        AgeRange: "20-30" | "30-40" | "40-50" | "50-60" | "60+" | "Not Specified";
        /**
         * Attire
         * @enum {string}
         */
        Attire: "Business Formal" | "Business Casual" | "Smart Casual" | "Creative Professional" | "Academic" | "Other";
        /**
         * Background
         * @enum {string}
         */
        Background: "Corporate Office" | "Plain Color" | "Outdoor" | "Studio-like" | "Library/Academic" | "Creative Space" | "Other";
        /** BasicInfo */
        BasicInfo: {
            purpose: components["schemas"]["Purpose"];
            attire: components["schemas"]["Attire"];
            background: components["schemas"]["Background"];
            vibe: components["schemas"]["Vibe"];
        };
        /** Body_start_run_api_v1_runs_post */
        Body_start_run_api_v1_runs_post: {
            /** Image */
            image: string;
            /** Goal */
            goal?: string | null;
            /** Preset */
            preset?: string | null;
            /** Reference Image */
            reference_image?: string | null;
        };
        /** CriterionScore */
        CriterionScore: {
            /** Criterion */
            criterion: string;
            /** Score */
            score: number;
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /**
         * Ethnicity
         * @enum {string}
         */
        Ethnicity: "Asian" | "Black" | "Caucasian" | "Hispanic" | "Middle Eastern" | "Mixed" | "Not Specified";
        /**
         * Gender
         * @enum {string}
         */
        Gender: "Male" | "Female" | "Non-binary" | "Not Specified";
        /**
         * GoalSpec
         * @description The complete portrait goal — the contract that drives the harness.
         */
        GoalSpec: {
            basic_info: components["schemas"]["BasicInfo"];
            advanced_settings?: components["schemas"]["AdvancedSettings"];
            additional_info?: components["schemas"]["AdditionalInfo"];
            metadata?: components["schemas"]["Metadata"];
            /** Generated Prompt */
            generated_prompt?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Backend Mode */
            backend_mode: string;
            /** Mllm Model */
            mllm_model: string;
            /** Editor Model */
            editor_model: string;
        };
        /** IterationDTO */
        IterationDTO: {
            /** Index */
            index: number;
            /** Instruction */
            instruction: string;
            /** Analysis */
            analysis: string;
            /** Confidence */
            confidence: number;
            /** Decision */
            decision: string;
            /** Accepted */
            accepted: boolean;
            /** Overall */
            overall: number;
            /** Identity */
            identity: number | null;
            /** Image Url */
            image_url: string;
            judge: components["schemas"]["JudgeResult"];
            /** Metrics */
            metrics: components["schemas"]["MetricResult"][];
        };
        /**
         * JudgeResult
         * @description The judge's per-criterion assessment of an edited image.
         */
        JudgeResult: {
            /** Scores */
            scores?: components["schemas"]["CriterionScore"][];
            /** Overall */
            overall: number;
            /**
             * Acceptable
             * @description Does it meet the bar for the requested portrait?
             */
            acceptable: boolean;
            /**
             * Feedback
             * @description Concrete guidance for the next edit.
             * @default
             */
            feedback: string;
        };
        /**
         * Lighting
         * @enum {string}
         */
        Lighting: "Natural Light" | "Studio Lighting" | "Soft Lighting" | "Dramatic Lighting" | "Golden Hour" | "Professional Flash";
        /** Metadata */
        Metadata: {
            /** Timestamp */
            timestamp?: string;
            /**
             * Version
             * @default 3.0
             */
            version: string;
            /**
             * Created By
             * @default APEX Portrait Generator
             */
            created_by: string;
        };
        /**
         * MetricResult
         * @description One metric's verdict on a candidate image (serializable into run JSON).
         */
        MetricResult: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Passed */
            passed: boolean;
            /** Threshold */
            threshold?: number | null;
            /**
             * Is Gate
             * @default true
             */
            is_gate: boolean;
            /**
             * Is Hard Gate
             * @default false
             */
            is_hard_gate: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * Mood
         * @enum {string}
         */
        Mood: "Professional" | "Casual" | "Serious" | "Energetic" | "Calm" | "Inspiring";
        /** PresetDTO */
        PresetDTO: {
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Attire */
            attire: string;
            /** Background */
            background: string;
            /** Vibe */
            vibe: string;
            /** Custom Notes */
            custom_notes: string;
            /** Description */
            description: string;
        };
        /**
         * Purpose
         * @enum {string}
         */
        Purpose: "LinkedIn" | "Resume" | "Corporate Website" | "Personal Branding" | "Business Card" | "Other";
        /**
         * Resolution
         * @enum {string}
         */
        Resolution: "1024x1024 (Standard)" | "1536x1024 (Wide)" | "1024x1536 (Portrait)" | "2048x2048 (High-Res)";
        /** RunDetailDTO */
        RunDetailDTO: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Current Iteration */
            current_iteration: number;
            /** Max Iterations */
            max_iterations: number;
            /** Final Index */
            final_index: number;
            /** Input Image Url */
            input_image_url: string;
            /** Final Image Url */
            final_image_url: string | null;
            /** Error */
            error: string | null;
            /** Iterations */
            iterations: components["schemas"]["IterationDTO"][];
            goal: components["schemas"]["GoalSpec"];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "completed" | "stopped_max_iters" | "stopped_identity" | "failed" | "cancelled";
        /** StartRunResponse */
        StartRunResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Status Url */
            status_url: string;
            /** Events Url */
            events_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Is Valid */
            is_valid: boolean;
            /** Message */
            message: string;
            /**
             * Missing Fields
             * @default []
             */
            missing_fields: string[];
        };
        /**
         * Vibe
         * @enum {string}
         */
        Vibe: "Confident" | "Friendly" | "Approachable" | "Authoritative" | "Creative" | "Sophisticated" | "Warm";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    options_api_v1_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetDTO"][];
                };
            };
        };
    };
    validate_api_v1_goal_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_start_run_api_v1_runs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    input_image_api_v1_runs__run_id__input_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iteration_image_api_v1_runs__run_id__iterations__index__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    final_image_api_v1_runs__run_id__final_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    save_profile_api_v1_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_profile_api_v1_profiles__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_v1_profiles__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
